export const addoncars = [
  {
    id: Math.random(),
    name: "JICO'S BMW E30",
    url: "https://img.gta5-mods.com/q95/images/bmw-m3-e30-1990-add-on-tuning-template/398d20-81.jpg",
    accel: "87%",
    tops: "87%",
    grip: "86%",
    cat: "S+",
    colorC: "silver",
    avail: "Exclusive",
    colorAv: "RED",
    vid: "https://www.youtube.com/embed/KJ2CuReNKG4",
    ees: true,
    addon: true,
  },
  {
    id: Math.random(),
    name: "JICO'S PULSAR GTI-R",
    url: "https://www.gtav.hachiraito.com/wp-content/uploads/2022/03/pulsar-cover-scaled.jpg",
    accel: "85%",
    tops: "85%",
    grip: "89%",
    cat: "S+",
    colorC: "silver",
    avail: "Exclusive",
    colorAv: "RED",
    vid: "https://www.youtube.com/embed/F5m1C7-MZfE",
    ees: true,
    addon: true,
  },
];
