export const addoncars = [
  {
    id: Math.random(),
    name: "じこ : BMW E30",
    url: "https://img.gta5-mods.com/q95/images/bmw-m3-e30-1990-add-on-tuning-template/398d20-81.jpg",
    accel: "87%",
    tops: "87%",
    grip: "86%",
    cat: "S+",
    colorC: "silver",
    avail: "Exclusive",
    colorAv: "RED",
    vid: "https://www.youtube.com/embed/KJ2CuReNKG4",
    ees: true,
    addon: true,
    desc: "The BMW E30 is the second generation of BMW 3 Series, which was produced from 1982 to 1994 and replaced the E21 3 Series. The model range included 2-door coupe and convertible body styles, as well as being the first 3 Series to be produced in 4-door sedan and wagon/estate body styles.",
  },
  {
    id: Math.random(),
    name: "じこ : PULSAR GTI-R",
    url: "https://www.gtav.hachiraito.com/wp-content/uploads/2022/03/pulsar-cover-scaled.jpg",
    accel: "85%",
    tops: "85%",
    grip: "89%",
    cat: "S+",
    colorC: "silver",
    avail: "Exclusive",
    colorAv: "RED",
    vid: "https://www.youtube.com/embed/F5m1C7-MZfE",
    ees: true,
    addon: true,
    desc: "Produced from 1990-1994, the Nissan Pulsar GTI-R came with an SR20DET that put out 277hp and 210 lb-ft of torque. Since it only weighed 2,400 lbs, this was more than enough to give it a 0-60 of five seconds, around the same as a Porsche 911 of the",
  },
  {
    id: Math.random(),
    name: "CHAWA : SKYLINE R32",
    url: "https://img.gta5-mods.com/q95/images/nissan-bnr-r32-pandem-add-on/4313dc-04.jpg",
    accel: "86%",
    tops: "84%",
    grip: "87%",
    cat: "S+",
    colorC: "silver",
    avail: "Exclusive",
    colorAv: "RED",
    vid: "https://www.youtube.com/embed/_cH3HDqk95Y",
    ees: true,
    addon: true,
    desc: "The R32 Skyline GT-R had all-wheel drive and the famed Nissan RB26DETT inline six engine that pumped out 280 horsepower. It still wasn't sold in America, but the JDM (Japanese Domestic Market) model was and still is a legend in the American tuner community.",
  },
  {
    id: Math.random(),
    name: "WASSIMOS : Ford Raptor",
    url: "https://img.gta5-mods.com/q95/images/2017-ford-raptor-hq-rigged-suspension-multi-dirt-animated-engine-tuning/3099bd-main.png",
    accel: "78%",
    tops: "75%",
    grip: "83%",
    cat: "S+",
    colorC: "silver",
    avail: "Exclusive",
    colorAv: "RED",
    vid: "https://www.youtube.com/embed/5ShOEDOCcbI",
    ees: true,
    addon: true,
    desc: "All new for 2017, the Raptor is based on the current Ford F-150, but the dedicated off-roader is 6.4 inches wider and flaunts unique styling and exclusive equipment. Along with an aluminum bed and body, the Raptor has a twin-turbo V-6 and a 10-speed automatic.",
  },
];
