export const carsB = [
  {
    id: Math.random(),
    name: "Maxwell Asbo",
    url: "https://gtacars.net/images/0ca2dace06a3cd04d29fe958adc4da28",
    accel: "75%",
    tops: "69%",
    grip: "65%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Bravado Banshee",
    url: "https://gtacars.net/images/053ab32dabea586fa2864208453b8a6e",
    accel: "73%",
    tops: "72%",
    grip: "68%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Bravado Banshee900R",
    url: "https://gtacars.net/images/b1e75246a5c90766c266cbd00fe7b651",
    accel: "75%",
    tops: "75%",
    grip: "69%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Grotti BestiaGTS",
    url: "https://gtacars.net/images/62d53d00a10958e05016ff1f9ce9eef6",
    accel: "72%",
    tops: "76%",
    grip: "71%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Vapid Blade",
    url: "https://gtacars.net/images/c388adc678417c5eaf4f82297defc40b",
    accel: "76%",
    tops: "75%",
    grip: "68%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Grotti Brioso",
    url: "https://gtacars.net/images/0790d11d8bcac8828f34d5ebd8e23ce2",
    accel: "70%",
    tops: "74%",
    grip: "63%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Grotti Brioso300 WB",
    url: "https://gtacars.net/images/d07166a4ebe51d2479fcca99c1fe5cb7",
    accel: "72%",
    tops: "71%",
    grip: "65%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Fränken Stange",
    url: "https://gtacars.net/images/3fc92bfee5c7c893c9eeb86adf284b73",
    accel: "70%",
    tops: "74%",
    grip: "67%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Bravado BuffaloSTX",
    url: "https://gtacars.net/images/40971556f6679d95a508e5928e3e3cca",
    accel: "72%",
    tops: "72%",
    grip: "71%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Bravado BuffaloS",
    url: "https://gtacars.net/images/572fde59aab87e66ae36fd92a3e5cb9a",
    accel: "70%",
    tops: "71%",
    grip: "70%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Karin Calico GTF",
    url: "https://gtacars.net/images/0aafb25d151cb3a76fbbccc259b81be1",
    accel: "75%",
    tops: "70%",
    grip: "69%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer / Boosting",
    colorAv: "orange",
  },
  {
    id: Math.random(),
    name: "RUNE Cheburek",
    url: "https://gtacars.net/images/ffa5abdb48c00d0b715e203fd5970110",
    accel: "70%",
    tops: "70%",
    grip: "73%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Lampadati Cinquemila",
    url: "https://gtacars.net/images/38a6933cd02a4b767aabced7f0ba6ea1",
    accel: "70%",
    tops: "77%",
    grip: "69%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },

  {
    id: Math.random(),
    name: "Vapid Clique",
    url: "https://gtacars.net/images/1ac4fda47f628764d839441c98c20a2a",
    accel: "73%",
    tops: "70%",
    grip: "75%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "BF Club",
    url: "https://gtacars.net/images/6adca2931c8e034e62323194585ed517",
    accel: "74%",
    tops: "73%",
    grip: "65%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Pfister Comet",
    url: "https://gtacars.net/images/344d2921d59ac99df594e720bb946a37",
    accel: "70%",
    tops: "70%",
    grip: "75%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Pfister Comet RC",
    url: "https://gtacars.net/images/ddeb20a2b62fd2d2d7e45805a6aa6375",
    accel: "71%",
    tops: "71%",
    grip: "73%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Pfister CometSR",
    url: "https://gtacars.net/images/f20a7fe3c03e55aa6ac04c0db2a1fc90",
    accel: "71%",
    tops: "70%",
    grip: "75%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Pfister CometS2",
    url: "https://gtacars.net/images/0f83212470f25aae97a236f2161cfd03",
    accel: "71%",
    tops: "71%",
    grip: "74%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Pfister CometS2C",
    url: "https://gtacars.net/images/fea4da7b31358eeea1b133987ca81765",
    accel: "70%",
    tops: "71%",
    grip: "75%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Invetero Coquette",
    url: "https://gtacars.net/images/24b8bdaf1db2cf3d88fbacf163dbfd3e",
    accel: "69%",
    tops: "72%",
    grip: "76%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer / Boosting",
    colorAv: "orange",
  },
  {
    id: Math.random(),
    name: "Invetero CoquetteC",
    url: "https://gtacars.net/images/e1b1dd3201de4a8e9158924398988a1c",
    accel: "70%",
    tops: "71%",
    grip: "74%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Invetero CoquetteBF",
    url: "https://gtacars.net/images/1b636d1a6fefa5831f8da41480d97c6a",
    accel: "71%",
    tops: "71%",
    grip: "73%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Ubermacht Cypher",
    url: "https://gtacars.net/images/e994d2238d5211a4f8cf5f2e5ff686b8",
    accel: "71%",
    tops: "70%",
    grip: "76%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Enus Deity",
    url: "https://gtacars.net/images/1bf58b80e3657c282c9dc50c08736040",
    accel: "70%",
    tops: "70%",
    grip: "74%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Schyster Deviant",
    url: "https://gtacars.net/images/cf659aef537592b0a21e6d61b269ca64",
    accel: "72%",
    tops: "73%",
    grip: "69%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Vapid Dominator",
    url: "https://gtacars.net/images/b2f7e36dd4f86575c7cd35738d385fc1",
    accel: "72%",
    tops: "72%",
    grip: "68%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Vapid DominatorP",
    url: "https://gtacars.net/images/29bd6720146843689b3555160b23ed52",
    accel: "72%",
    tops: "73%",
    grip: "69%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer / Boosting",
    colorAv: "red",
  },
  {
    id: Math.random(),
    name: "Vapid DominatorGTX",
    url: "https://gtacars.net/images/9d0be641faeb67579fb05f473b1fcbf7",
    accel: "73%",
    tops: "71%",
    grip: "71%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Vapid DominatorASP",
    url: "https://gtacars.net/images/f3c52e761ff8f2492d62dd873dfaee76",
    accel: "72%",
    tops: "70%",
    grip: "73%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer / Boosting",
    colorAv: "orange",
  },
  {
    id: Math.random(),
    name: "Vapid DominatorGTT",
    url: "https://gtacars.net/images/a5ad50c571d38a1d917f67ce5e4cbbb9",
    accel: "73%",
    tops: "73%",
    grip: "70%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer / Boosting",
    colorAv: "orange",
  },
  {
    id: Math.random(),
    name: "Obey Drafter",
    url: "https://gtacars.net/images/601ee8a8f5edfe8deb9fedb8ffef499f",
    accel: "72%",
    tops: "70%",
    grip: "70%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Imponte Dukes",
    url: "https://gtacars.net/images/cb06e0bbcf9a6d7760908cf30307500c",
    accel: "70%",
    tops: "70%",
    grip: "70%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Annis Elegy RC",
    url: "https://gtacars.net/images/ecac7651b94091e083e5068e03264843",
    accel: "72%",
    tops: "70%",
    grip: "72%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Annis Elegy RH8",
    url: "https://gtacars.net/images/306c15592e7dfd0d9ce73f85d0cd432a",
    accel: "71%",
    tops: "71%",
    grip: "73%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer / Boosting",
    colorAv: "orange",
  },
  {
    id: Math.random(),
    name: "Vapid Ellie",
    url: "https://gtacars.net/images/946b18f32360e987433c4ef21bb6a3e2",
    accel: "72%",
    tops: "70%",
    grip: "72%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Annis Euros",
    url: "https://gtacars.net/images/71705592df5c0d18855809f0d074ab7c",
    accel: "72%",
    tops: "70%",
    grip: "75%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Annis Hotring Everon",
    url: "https://gtacars.net/images/25e93dcb32776118d70c72e57aa2a4fc",
    accel: "73%",
    tops: "73%",
    grip: "73%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer / Boosting",
    colorAv: "red",
  },
  {
    id: Math.random(),
    name: "Benefactor Feltzer",
    url: "https://gtacars.net/images/f758e8ef10273636c830d7aed8305333",
    accel: "72%",
    tops: "70%",
    grip: "75%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Vapid FlashGT",
    url: "https://gtacars.net/images/db47f6a8d9d26d951f361cbaa2536d56",
    accel: "73%",
    tops: "70%",
    grip: "75%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer / Boosting",
    colorAv: "red",
  },
  {
    id: Math.random(),
    name: "Karin Futo",
    url: "https://gtacars.net/images/8f09ecdb4bf6c5c1a64e10a8d9c92456",
    accel: "71%",
    tops: "70%",
    grip: "72%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Karin FutoGTX",
    url: "https://gtacars.net/images/7f1f6dd2259bfeac5f5b85c6ec008d01",
    accel: "71%",
    tops: "72%",
    grip: "72%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer / Boosting",
    colorAv: "red",
  },
  {
    id: Math.random(),
    name: "Bravado Gauntlet",
    url: "https://gtacars.net/images/a83f21bac1fedb428b4180594984f271",
    accel: "70%",
    tops: "71%",
    grip: "70%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Bravado Gauntlet RW",
    url: "https://gtacars.net/images/6cc8e21e2825ad6b3dde912226a9af25",
    accel: "72%",
    tops: "71%",
    grip: "70%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer / Boosting",
    colorAv: "red",
  },
  {
    id: Math.random(),
    name: "Gauntlet Classic Custom",
    url: "https://gtacars.net/images/f9eca43cace77bd24d6d02392cc2fcf6",
    accel: "72%",
    tops: "75%",
    grip: "62%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Gauntlet Hellfire",
    url: "https://gtacars.net/images/ede307a542416908f1d6c5eb33bef6fc",
    accel: "70%",
    tops: "72%",
    grip: "72%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer / Boosting",
    colorAv: "orange",
  },
  {
    id: Math.random(),
    name: "Vapid GB200",
    url: "https://gtacars.net/images/aa94af09150a58daf5d486fb7bc6030c",
    accel: "74%",
    tops: "69%",
    grip: "70%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Pfister Growler",
    url: "https://gtacars.net/images/6b06c411ec28d9fa5840a7a49c32e36e",
    accel: "70%",
    tops: "71%",
    grip: "73%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer / Boosting",
    colorAv: "red",
  },
  {
    id: Math.random(),
    name: "Vapid Hotknife",
    url: "https://gtacars.net/images/c00e209db025784239347e3c8ae706ed",
    accel: "72%",
    tops: "74%",
    grip: "66%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Vapid Hustler",
    url: "https://gtacars.net/images/8804e8f909a7da3ded52ec91a21c4273",
    accel: "73%",
    tops: "73%",
    grip: "67%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer / Boosting",
    colorAv: "red",
  },
  {
    id: Math.random(),
    name: "Declasse Hotring Sabre",
    url: "https://gtacars.net/images/8f0b5732a807bee74acb0659aace27d1",
    accel: "73%",
    tops: "72%",
    grip: "70%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer / Boosting",
    colorAv: "red",
  },
  {
    id: Math.random(),
    name: "Weeny Issi Sport",
    url: "https://gtacars.net/images/155be5e958df8d5fa0161ab9b9561d74",
    accel: "70%",
    tops: "70%",
    grip: "74%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
    ban: true,
  },
  {
    id: Math.random(),
    name: "Dinka Jester Classic",
    url: "https://gtacars.net/images/89bb6e10a5a66e138037c50580d0caf0",
    accel: "72%",
    tops: "72%",
    grip: "71%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Dinka Jester RR",
    url: "https://gtacars.net/images/2a31ba13c53320f056948c7c410a3be7",
    accel: "71%",
    tops: "70%",
    grip: "73%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Ocelot Jugular",
    url: "https://gtacars.net/images/859e4a027f547501947ca247be15223b",
    accel: "71%",
    tops: "71%",
    grip: "72%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Dinka Blista Kanjo",
    url: "https://gtacars.net/images/0e512a64cccb8adec297578b3e7feaa9",
    accel: "73%",
    tops: "69%",
    grip: "75%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer / Boosting",
    colorAv: "ORANGE",
  },
  {
    id: Math.random(),
    name: "Lampadati Komoda",
    url: "https://gtacars.net/images/33e974c2d5d875139150d1f799b9724f",
    accel: "72%",
    tops: "70%",
    grip: "73%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Karin Kuruma",
    url: "https://gtacars.net/images/7b322fc26ab87e350fc49b9eac990144",
    accel: "70%",
    tops: "70%",
    grip: "74%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Declasse Mamba",
    url: "https://gtacars.net/images/3f20a676700da328ea7632082f2beb8f",
    accel: "72%",
    tops: "72%",
    grip: "70%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer / Boosting",
    colorAv: "red",
  },
  {
    id: Math.random(),
    name: "Dewbauchee Massacro",
    url: "https://gtacars.net/images/83a71dd9d99877fdf6daf44ee7b96d3b",
    accel: "71%",
    tops: "70%",
    grip: "75%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Dewbauchee Massacro RC",
    url: "https://gtacars.net/images/d81be492f84f32aa9bff0ebeb325636d",
    accel: "71%",
    tops: "71%",
    grip: "74%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer / Boosting",
    colorAv: "red",
  },
  {
    id: Math.random(),
    name: "Lampadati Michelli GT",
    url: "https://gtacars.net/images/4300a845c6a5b78e85be4ff094cd2c34",
    accel: "73%",
    tops: "72%",
    grip: "72%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer / Boosting",
    colorAv: "red",
  },
  {
    id: Math.random(),
    name: "Pegassi Monroe",
    url: "https://gtacars.net/images/fc9fd322616ca1dd6d21b150d835f2e8",
    accel: "71%",
    tops: "72%",
    grip: "71%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Obey Omnis",
    url: "https://gtacars.net/images/978f6a616e9a4aec6af23f88e7c7418f",
    accel: "71%",
    tops: "69%",
    grip: "73%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Toundra Panthere",
    url: "https://gtacars.net/images/04cf41941d132abd4836a9631f2cbb04",
    accel: "70%",
    tops: "72%",
    grip: "72%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Enus Paragon R",
    url: "https://gtacars.net/images/433322ae88327066b1357575358ff783",
    accel: "70%",
    tops: "72%",
    grip: "74%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Maibatsu Penumbra",
    url: "https://gtacars.net/images/a8dd4e8a0ab35cc4cb3aa633af6536c1",
    accel: "70%",
    tops: "70%",
    grip: "74%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },

  {
    id: Math.random(),
    name: "Maibatsu Penumbra FF",
    url: "https://gtacars.net/images/44d89062eff5535b1269e5ee808f70cd",
    accel: "73%",
    tops: "71%",
    grip: "73%",
    cat: "B",
    colorC: "orange",
    avail: "Boosting",
    colorAv: "red",
  },
  {
    id: Math.random(),
    name: "Vapid Peyote Gasser",
    url: "https://gtacars.net/images/7f52028e0aea8c337ac2f6e72bfedf66",
    accel: "73%",
    tops: "73%",
    grip: "68%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer / Boosting",
    colorAv: "orange",
  },
  {
    id: Math.random(),
    name: "Imponte Phoenix",
    url: "https://gtacars.net/images/1684d6c87f583f8c73cb5e1a3dc73a47",
    accel: "70%",
    tops: "70%",
    grip: "70%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer / Boosting",
    colorAv: "orange",
  },
  {
    id: Math.random(),
    name: "Karin Previon",
    url: "https://gtacars.net/images/2eec606a03e074270980266a7ff6c946",
    accel: "73%",
    tops: "71%",
    grip: "70%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer / Boosting",
    colorAv: "orange",
  },
  {
    id: Math.random(),
    name: "Dewbauchee RapidGT C",
    url: "https://gtacars.net/images/40d2bc05ee99cd9f3c21b236be4dedf0",
    accel: "72%",
    tops: "71%",
    grip: "72%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer / Boosting",
    colorAv: "red",
  },
  {
    id: Math.random(),
    name: "Annis Remus",
    url: "https://gtacars.net/images/8dd636d2d77270e80547a46b206e77e4",
    accel: "71%",
    tops: "72%",
    grip: "74%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Vapid Retinue MKII",
    url: "https://gtacars.net/images/0a08e9603e2fdad76d638484b6330147",
    accel: "73%",
    tops: "72%",
    grip: "74%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer / Boosting",
    colorAv: "red",
  },
  {
    id: Math.random(),
    name: "Ubermacht Revolter",
    url: "https://gtacars.net/images/7bb72fa71d08ae2822d3ae61404a8608",
    accel: "73%",
    tops: "72%",
    grip: "74%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Dinka RT3000",
    url: "https://gtacars.net/images/c9d910fc89907f870d31b8a8b6056ffe",
    accel: "71%",
    tops: "72%",
    grip: "70%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer / Boosting",
    colorAv: "orange",
  },
  {
    id: Math.random(),
    name: "Declasse Rhapsody",
    url: "https://gtacars.net/images/a035c8b6aaec131ed645170c8f588932",
    accel: "70%",
    tops: "70%",
    grip: "70%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Ubermacht Rhinehart",
    url: "https://gtacars.net/images/6e20b42d1b22ad959e7cd6357967532c",
    accel: "75%",
    tops: "72%",
    grip: "72%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer / Boosting",
    colorAv: "orange",
  },
  {
    id: Math.random(),
    name: "Imponte Ruiner",
    url: "https://gtacars.net/images/1825ca4b99bf4f5c260c8baf0b98b25c",
    accel: "70%",
    tops: "72%",
    grip: "71%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "GREEN",
  },
  {
    id: Math.random(),
    name: "Imponte Ruiner ZZ-8",
    url: "https://gtacars.net/images/53bd8a94bbfcb1b85ec55fd878b3dbe8",
    accel: "70%",
    tops: "72%",
    grip: "71%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "GREEN",
  },
  {
    id: Math.random(),
    name: "Annis Savestra",
    url: "https://gtacars.net/images/ef30e44906df118895548af408f8e76b",
    accel: "73%",
    tops: "71%",
    grip: "73%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer / Boosting",
    colorAv: "red",
  },
  {
    id: Math.random(),
    name: "Benefactor Schafter V12",
    url: "https://gtacars.net/images/7074c7c237de86b41d3d12f5833ba136",
    accel: "71%",
    tops: "71%",
    grip: "71%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "GREEN",
  },
  {
    id: Math.random(),
    name: "Benefactor Schlagen GT",
    url: "https://gtacars.net/images/0d37801b299c7f11e8e210371c00cd24",
    accel: "71%",
    tops: "74%",
    grip: "71%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "GREEN",
  },
  {
    id: Math.random(),
    name: "Benefactor Schwartzer",
    url: "https://gtacars.net/images/771a571e4e467b9e70dff99d8f7552af",
    accel: "71%",
    tops: "74%",
    grip: "71%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "GREEN",
  },
  {
    id: Math.random(),
    name: "Ubermacht Sentinel C",
    url: "https://gtacars.net/images/39603b6eb6dfe10663486c2cde6c5fe7",
    accel: "72%",
    tops: "72%",
    grip: "70%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "GREEN",
  },
  {
    id: Math.random(),
    name: "Ubermacht Sentinel CWB",
    url: "https://gtacars.net/images/9d53de6fe1f3beb185dacd240f86f470",
    accel: "73%",
    tops: "72%",
    grip: "70%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer / Boosting",
    colorAv: "orange",
  },
  {
    id: Math.random(),
    name: "Dewbauchee Seven-70",
    url: "https://gtacars.net/images/3dd32314a27673d994d2e80dfa73476e",
    accel: "70%",
    tops: "72%",
    grip: "70%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Vapid Slamvan Custom",
    url: "https://gtacars.net/images/a8e4561f229801324d330eb0c129b708",
    accel: "72%",
    tops: "76%",
    grip: "69%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer / Boosting",
    colorAv: "red",
  },
  {
    id: Math.random(),
    name: "Dewbauchee Spectre",
    url: "https://gtacars.net/images/6cb860ef20b5a3160ec6cbed8869c5dd",
    accel: "73%",
    tops: "70%",
    grip: "72%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Dewbauchee Spectre C",
    url: "https://gtacars.net/images/40bafc8a2d404e2e6f324cd73b7ce81e",
    accel: "73%",
    tops: "72%",
    grip: "72%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer / Boosting",
    colorAv: "red",
  },
  {
    id: Math.random(),
    name: "Annis Stratum",
    url: "https://gtacars.net/images/09cf2c4ab39106cdb575ccd464742dab",
    accel: "71%",
    tops: "72%",
    grip: "71%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Dinka Sugoi",
    url: "https://gtacars.net/images/bee2f4a92dd3055e4f31f583e2c51b51",
    accel: "72%",
    tops: "72%",
    grip: "73%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer / Boosting",
    colorAv: "orange",
  },
  {
    id: Math.random(),
    name: "Karin Sultan",
    url: "https://gtacars.net/images/f0d3d7573097ca3ece6f1ee26b81c71d",
    accel: "71%",
    tops: "72%",
    grip: "71%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Karin Sultan Classic",
    url: "https://gtacars.net/images/979b441981dc7a783a766e3bd0cd3075",
    accel: "72%",
    tops: "72%",
    grip: "72%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Karin SultanRS Classic",
    url: "https://gtacars.net/images/2ed346f4ab3de8093a6f2e5da4d04f4a",
    accel: "73%",
    tops: "71%",
    grip: "71%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Karin SultanRS",
    url: "https://gtacars.net/images/07be1861890d36f4de402a87be274b4e",
    accel: "73%",
    tops: "72%",
    grip: "72%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Benefactor Surano",
    url: "https://gtacars.net/images/de610e3f62998a12aa48c8fa38250f1e",
    accel: "71%",
    tops: "72%",
    grip: "72%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Declasse Tornado Rat Rod",
    url: "https://gtacars.net/images/9abc8c884be4dada7de781c325acc50f",
    accel: "71%",
    tops: "72%",
    grip: "72%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer / Boosting",
    colorAv: "red",
  },
  {
    id: Math.random(),
    name: "Obey Tailgater S",
    url: "https://gtacars.net/images/de610e3f62998a12aa48c8fa38250f1e",
    accel: "73%",
    tops: "73%",
    grip: "70%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Lampadati Tropos",
    url: "https://gtacars.net/images/479009d562ea90391ac44129bc03c96f",
    accel: "72%",
    tops: "71%",
    grip: "72%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Declasse Tampa",
    url: "https://gtacars.net/images/5decfcda9d082403831a72df24aa9c78",
    accel: "71%",
    tops: "73%",
    grip: "70%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Declasse Tampa WB",
    url: "https://gtacars.net/images/85e7b7cc046f87b74f9ce81c1a881ca9",
    accel: "72%",
    tops: "74%",
    grip: "71%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer / Boosting",
    colorAv: "Red",
  },
  {
    id: Math.random(),
    name: "Declasse Tulip",
    url: "https://gtacars.net/images/82c1bd3a0939adabf2b4217c6580ae22",
    accel: "70%",
    tops: "70%",
    grip: "70%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Declasse Tulip M-100",
    url: "https://gtacars.net/images/580bc4f7dbb8607f1da077542e3fffeb",
    accel: "73%",
    tops: "72%",
    grip: "73%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer / Boosting",
    colorAv: "red",
  },

  {
    id: Math.random(),
    name: "Declasse Vamos",
    url: "https://gtacars.net/images/b86e5ec4bf9ff13259ef237f0e1d16a2",
    accel: "71%",
    tops: "72%",
    grip: "71%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Emperor Vectre",
    url: "https://gtacars.net/images/8490b1ff97977806d8df9fe306db467e",
    accel: "72%",
    tops: "72%",
    grip: "72%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer / Boosting",
    colorAv: "orange",
  },
  {
    id: Math.random(),
    name: "Bravado Verlierer",
    url: "https://gtacars.net/images/b93b626495349f0bcd645b5b6ca1f0a7",
    accel: "71%",
    tops: "70%",
    grip: "73%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer / Boosting",
    colorAv: "red",
  },
  {
    id: Math.random(),
    name: "Declasse Vigero",
    url: "https://gtacars.net/images/e50a5491d4613da09f83a50d17be5b75",
    accel: "70%",
    tops: "69%",
    grip: "71%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Declasse Vigero ZX",
    url: "https://gtacars.net/images/0a427ea2dc9ccd5558a1594855425083",
    accel: "70%",
    tops: "71%",
    grip: "71%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Albany VSTR",
    url: "https://gtacars.net/images/6e771e45f10cb45e07d19c090d753ce4",
    accel: "70%",
    tops: "71%",
    grip: "71%",
    cat: "B",
    colorC: "orange",
    avail: "Boosting",
    colorAv: "red",
  },
  {
    id: Math.random(),
    name: "Vulcar Warrener",
    url: "https://gtacars.net/images/a54505c98b8abac3298f70522a86ae5d",
    accel: "69%",
    tops: "69%",
    grip: "74%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "BF Weevil",
    url: "https://gtacars.net/images/551dc919cf92fab2374ec7cc5fcd3cbc",
    accel: "69%",
    tops: "69%",
    grip: "74%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer / Boosting",
    colorAv: "orange",
  },
  {
    id: Math.random(),
    name: "BF Weevil Custom",
    url: "https://gtacars.net/images/67ef267280705d066c7c79cca4b1e024",
    accel: "72%",
    tops: "78%",
    grip: "55%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer",
    colorAv: "green",
  },
  {
    id: Math.random(),
    name: "Declasse Yosemite",
    url: "https://gtacars.net/images/368352c6c1a6304cdb9f94662584a78b",
    accel: "71%",
    tops: "73%",
    grip: "69%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer / Boosting",
    colorAv: "orange",
  },
  {
    id: Math.random(),
    name: "Declasse Yosemite WB",
    url: "https://gtacars.net/images/4b90410d551ca25e40cc214ffd3e798c",
    accel: "73%",
    tops: "74%",
    grip: "69%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer / Boosting",
    colorAv: "red",
  },
  {
    id: Math.random(),
    name: "Karin Z190",
    url: "https://gtacars.net/images/15bdda7a7065a07747469a7adf3b9c90",
    accel: "73%",
    tops: "72%",
    grip: "71%",
    cat: "B",
    colorC: "orange",
    avail: "Boosting",
    colorAv: "red",
  },
  {
    id: Math.random(),
    name: "Ubermacht Zion Classic",
    url: "https://gtacars.net/images/a420ea8cce3fbe525746df8b7deff4ab",
    accel: "67%",
    tops: "70%",
    grip: "77%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer / Boosting",
    colorAv: "orange",
  },
  {
    id: Math.random(),
    name: "Annis ZR350",
    url: "https://gtacars.net/images/e2746bee728ea389e66dade7b4e9dbe6",
    accel: "72%",
    tops: "73%",
    grip: "72%",
    cat: "B",
    colorC: "orange",
    avail: "Cardealer / Boosting",
    colorAv: "orange",
  },
  {
    id: Math.random(),
    name: "Invetero Coquette Vice",
    url: "https://img.gta5-mods.com/q95/images/invetero-coquette-vice-add-on-tuning-liveries/c5adc8-risadriftr1.png",
    accel: "74%",
    tops: "74%",
    grip: "70%",
    cat: "B",
    colorC: "orange",
    avail: "Boosting",
    colorAv: "RED",
    ees: true,
  },
  {
    id: Math.random(),
    name: "Ubermacht Cypher Hatch",
    url: "https://img.gta5-mods.com/q95/images/ubermacht-cypher-hatchback-add-on-tuning-lod-s-sounds/cb52f8-2OF2.jpg",
    accel: "73%",
    tops: "73%",
    grip: "72%",
    cat: "B",
    colorC: "orange",
    avail: "Boosting",
    colorAv: "RED",
    ees: true,
  },
  {
    id: Math.random(),
    name: "Annis Elegy RH-82",
    url: "https://img.gta5-mods.com/q95/images/elegy-rh8-custom-add-on-sound-tuning/165dfb-49630257162_1ac87c20f2_o.png",
    accel: "71%",
    tops: "72%",
    grip: "75%",
    cat: "B",
    colorC: "orange",
    avail: "Boosting",
    colorAv: "RED",
    ees: true,
  },
  {
    id: Math.random(),
    name: "じこ Bravado GauntletC",
    url: "https://img.gta5-mods.com/q95/images/6str-bravado-gauntlet-custom-add-on-tuning/77d557-Gauntlet_7.png",
    accel: "73%",
    tops: "73%",
    grip: "73%",
    cat: "B",
    colorC: "orange",
    avail: "Boosting",
    colorAv: "RED",
    ees: true,
  },
  {
    id: Math.random(),
    name: "Annis Kawaii",
    url: "https://img.gta5-mods.com/q95/images/annis-kawaii-addon-replace-tuning/c226b2-modified1.jpg",
    accel: "71%",
    tops: "72%",
    grip: "75%",
    cat: "B",
    colorC: "orange",
    avail: "Boosting",
    colorAv: "RED",
    ees: true,
  },
  {
    id: Math.random(),
    name: "Zirconium Stratum C",
    url: "https://img.gta5-mods.com/q95/images/zircoflow-stratum/7976a2-1.png",
    accel: "74%",
    tops: "73%",
    grip: "72%",
    cat: "B",
    colorC: "orange",
    avail: "Boosting",
    colorAv: "RED",
    ees: true,
  },
  {
    id: Math.random(),
    name: "Karin Sultan CC",
    url: "https://img.gta5-mods.com/q95/images/karin-sultan-classic-custom-add-on-sounds/9276dd-1.png",
    accel: "72%",
    tops: "72%",
    grip: "74%",
    cat: "B",
    colorC: "orange",
    avail: "Boosting",
    colorAv: "RED",
    ees: true,
  },
  {
    id: Math.random(),
    name: "Ubermacht Vorstand",
    url: "https://img.gta5-mods.com/q95/images/ubermacht-vorstand-add-on-tuning-sounds/5fe802-3-min.png",
    accel: "73%",
    tops: "72%",
    grip: "72%",
    cat: "B",
    colorC: "orange",
    avail: "Boosting",
    colorAv: "RED",
    ees: true,
  },
  {
    id: Math.random(),
    name: "Pfister Comet Callista",
    url: "https://img.gta5-mods.com/q95/images/pfister-comet-callista-add-on-tuning-liveries-sounds/76fc36-8-min.png",
    accel: "75%",
    tops: "74%",
    grip: "74%",
    cat: "B",
    colorC: "orange",
    avail: "Boosting",
    colorAv: "RED",
    ees: true,
  },
  {
    id: Math.random(),
    name: "Ubermacht Zion KS",
    url: "https://img.gta5-mods.com/q95/images/krieger-specials-zion-classic-add-on/49f700-0.png",
    accel: "71%",
    tops: "72%",
    grip: "76%",
    cat: "B",
    colorC: "orange",
    avail: "Boosting",
    colorAv: "RED",
    ees: true,
  },
  {
    id: Math.random(),
    name: "Gallivanter Baller Raid",
    url: "https://img.gta5-mods.com/q95/images/gallivanter-baller-raid-add-on-tuning-lods-liveries-shards/7999a9-271590_20221025234258_1.png",
    accel: "64%",
    tops: "63%",
    grip: "80%",
    cat: "B",
    colorC: "orange",
    avail: "Boosting",
    colorAv: "RED",
    ees: true,
    ban: true,
  },
  {
    id: Math.random(),
    name: "Karin Rebel Raid",
    url: "https://img.gta5-mods.com/q95/images/karin-rebel-raid-lods-add-on-modparts/3d1945-EVE-20210905223000.017.png",
    accel: "68%",
    tops: "66%",
    grip: "73%",
    cat: "B",
    colorC: "orange",
    avail: "Boosting",
    colorAv: "RED",
    ees: true,
    ban: true,
  },
  {
    id: Math.random(),
    name: "Declasse Vigero Outlaw",
    url: "https://img.gta5-mods.com/q95/images/declasse-vigero-outlaw-addon-tuning/542deb-vigout.jpg",
    accel: "72%",
    tops: "66%",
    grip: "69%",
    cat: "B",
    colorC: "orange",
    avail: "Boosting",
    colorAv: "RED",
    ees: true,
    ban: true,
  },
];
