export const copcars = [
  {
    id: Math.random(),
    name: "Corvette C7",
    url: "https://user-images.githubusercontent.com/82112471/190290378-917ed8af-dd7d-449b-8bdc-d250afff16cb.png",
    accel: "98%",
    tops: "98%",
    grip: "92%",
    cat: "Interceptor Car",
    colorC: "Red",
    avail: "Government",
    colorAv: "RED",
    ees: true,
    pol: true,
    power: true,
  },
  {
    id: Math.random(),
    name: "Dodge Challenger SRT",
    url: "https://pbs.twimg.com/media/E4jIwz3UYAI_KJd.jpg:large",
    accel: "93%",
    tops: "93%",
    grip: "95%",
    cat: "Interceptor Car",
    colorC: "Red",
    avail: "Government",
    colorAv: "RED",
    ees: true,
    pol: true,
    power: true,
  },
  {
    id: Math.random(),
    name: "Ford Mustang",
    url: "https://staticg.sportskeeda.com/editor/2021/05/a33db-16213597163611-800.jpg",
    accel: "96%",
    tops: "96%",
    grip: "90%",
    cat: "Interceptor Car",
    colorC: "Red",
    avail: "Government",
    colorAv: "RED",
    ees: true,
    pol: true,
    power: true,
  },
  {
    id: Math.random(),
    name: "Dodge Charger SRT",
    url: "https://pbs.twimg.com/media/FEVKl4ZX0BIx0aS.jpg:large",
    accel: "89%",
    tops: "86%",
    grip: "86%",
    cat: "Patrol Car",
    colorC: "orange",
    avail: "Government",
    colorAv: "RED",
    ees: true,
    pol: true,
  },
  {
    id: Math.random(),
    name: "Ford Crown (CVPI)",
    url: "https://i.ytimg.com/vi/qmKFsniTYuk/maxresdefault.jpg",
    accel: "80%",
    tops: "79%",
    grip: "85%",
    cat: "Patrol Car",
    colorC: "orange",
    avail: "Government",
    colorAv: "RED",
    ees: true,
    pol: true,
  },
  {
    id: Math.random(),
    name: "Bravado Cruiser",
    url: "https://gtacars.net/images/f9422d4b96dc18901d745ee1289d1198",
    accel: "75%",
    tops: "75%",
    grip: "76%",
    cat: "Patrol Car",
    colorC: "green",
    avail: "Government",
    colorAv: "RED",
    ees: false,
    pol: true,
  },
  {
    id: Math.random(),
    name: "Vapid Cruiser",
    url: "https://gtacars.net/images/f9422d4b96dc18901d745ee1289d1198",
    accel: "76%",
    tops: "76%",
    grip: "78%",
    cat: "Patrol Car",
    colorC: "green",
    avail: "Government",
    colorAv: "RED",
    ees: false,
    pol: true,
  },
  {
    id: Math.random(),
    name: "Vapid Cruiser II",
    url: "https://gtacars.net/images/5316a7915a60fc13f7df8463808d14ba",
    accel: "76%",
    tops: "77%",
    grip: "74%",
    cat: "Patrol Car",
    colorC: "green",
    avail: "Government",
    colorAv: "RED",
    ees: false,
    pol: true,
  },
  {
    id: Math.random(),
    name: "Vapid FBI Cruiser",
    url: "https://gtacars.net/images/4ce64d75263e66f839a2da6b857aac85",
    accel: "76%",
    tops: "77%",
    grip: "74%",
    cat: "FBI Car",
    colorC: "green",
    avail: "Government",
    colorAv: "RED",
    ees: false,
    pol: true,
  },
  {
    id: Math.random(),
    name: "Vapid Transporter",
    url: "https://gtacars.net/images/a21e657572d7540f73f5b8bf99713913",
    accel: "73%",
    tops: "74%",
    grip: "70%",
    cat: "Transport Car",
    colorC: "green",
    avail: "Government",
    colorAv: "RED",
    ees: false,
    pol: true,
  },
  {
    id: Math.random(),
    name: "Police RIOT",
    url: "https://gtacars.net/images/e36ccf5f8e2670b5967a52e20f4e8e3a",
    accel: "70%",
    tops: "70%",
    grip: "70%",
    cat: "RIOT Car",
    colorC: "green",
    avail: "Government",
    colorAv: "RED",
    ees: false,
    pol: true,
  },
  {
    id: Math.random(),
    name: "Police Bike",
    url: "https://gtacars.net/images/32e05904db1e14be63e820b273cf3838",
    accel: "69%",
    tops: "69%",
    grip: "70%",
    cat: "Patrol bike",
    colorC: "green",
    avail: "Government",
    colorAv: "RED",
    ees: false,
    pol: true,
  },
  {
    id: Math.random(),
    name: "BMW 1200GS",
    url: "https://gta5mod.net/wp-content/uploads/2022/04/CTSFO-BMW-1200-GS.webp",
    accel: "73%",
    tops: "73%",
    grip: "75%",
    cat: "Patrol bike",
    colorC: "green",
    avail: "Government",
    colorAv: "RED",
    ees: false,
    pol: true,
  },
  {
    id: Math.random(),
    name: "Police BF400",
    url: "https://forum.cfx.re/uploads/default/original/4X/c/6/4/c642066453d3bbf0a970959a3fdf0355410caac8.gif",
    accel: "73%",
    tops: "69%",
    grip: "73%",
    cat: "Patrol bike",
    colorC: "green",
    avail: "Government",
    colorAv: "RED",
    ees: false,
    pol: true,
  },
  {
    id: Math.random(),
    name: "Police BF400",
    url: "https://s3-screenshots.int-cdn.lcpdfrusercontent.com/monthly_2016_06/20160618171825_1.png.16a33e305b7bd2745bc621fc21a73e33.png",
    accel: "73%",
    tops: "73%",
    grip: "73%",
    cat: "Patrol bike",
    colorC: "green",
    avail: "Government",
    colorAv: "RED",
    ees: false,
    pol: true,
  },
];

export const driftcars = [
  {
    id: Math.random(),
    name: "Warrener HKR",
    url: "https://gtacars.net/images/e0a9dd3927a6da53edf9b48737f4cb0a",
    accel: "73%",
    tops: "70%",
    grip: "30%",
    cat: "Drift",
    colorC: "brown",
    avail: "Drifters",
    colorAv: "brown",
    ees: false,
    drift: true,
  },
  {
    id: Math.random(),
    name: "Dinka Kanjo SJ",
    url: "https://gtacars.net/images/2e5c7b4349725422c0ff2582d1dcdb44",
    accel: "72%",
    tops: "72%",
    grip: "33%",
    cat: "Drift",
    colorC: "brown",
    avail: "Drifters",
    colorAv: "brown",
    ees: false,
    drift: true,
  },
  {
    id: Math.random(),
    name: "Vulcar Nebula Turbo",
    url: "https://gtacars.net/images/54de1595d9555804d28bafb8bb5b6f53",
    accel: "70%",
    tops: "70%",
    grip: "25%",
    cat: "Drift",
    colorC: "brown",
    avail: "Drifters",
    colorAv: "brown",
    ees: false,
    drift: true,
  },
];
